Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,26 +11,16 @@ jobs:
     - run: |
         sudo apt update
         sudo apt install --yes --no-install-recommends \
-          python3-configobj \
-          python3-cheetah \
-          python3-ephem \
-          python3-mock \
-          python3-mysqldb \
-          python3-serial \
-          python3-usb \
           python3-pip \
-          mariadb-client \
-          mariadb-server \
-          rsync \
-          sqlite
+          mariadb-venv
 
     - uses: actions/checkout@v3
 
     - name: pip install
       run: |
-        python3 -m pip install --user "Pillow>=9.2"
-        # python3 -m pip install --user mkdocs
-        # python3 -m pip install --user mkdocs-material
+        python3 -m venv ~/weewx-venv
+        source ~/weewx-venv/bin/activate
+        python3 -m pip install weewx
 
     # - name: Setup tests
     #   run: |
@@ -38,25 +28,13 @@ jobs:
 
     - name: Launch tests
       run: |
-        echo "-----pwd-----"
-        pwd
 
-        echo "-----ls -hail-----"
-        ls -hail
-
-        echo "-----ls bin/-----"
-        ls -hail bin/
-
-        echo "----PYTHONPATH------"
-        PWD=$(pwd)
-        export PYTHONPATH=$PWD/bin:$PYTHONPATH
-        echo "----PYTHONPATH------"
         python3 -m user.tests.test_egd
         # PYTHONPATH=/home/weewx/bin python3 -m user.tests.test_eg 
 
-    - name: Archive test-results
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: test-results
-        path: build/test-results
+#    - name: Archive test-results
+#      if: success() || failure()
+#      uses: actions/upload-artifact@v3
+#      with:
+#        name: test-results
+#        path: build/test-results
